domain_path: /home/user/work/FY25/03_project/VoiceNote/sw/voice_note_platform/zynq_fsbl/zynq_fsbl_bsp
app_src_dir: /home/user/Xilinx/Vitis/2024.2/data/embeddedsw/lib/sw_apps/zynq_fsbl
template: zynq_fsbl
lang: c
